name: Release

on:
  push:
    branches: [main]

concurrency: release

jobs:
  ci:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/ci.yml

  release:
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Create release
        id: release
        uses: googleapis/release-please-action@v4

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v7
        with:
          ref: ${{ steps.release.outputs.sha }}

      - name: Set up pnpm
        if: ${{ steps.release.outputs.release_created }}
        uses: pnpm/action-setup@v6

      - name: Set up Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm install --frozen-lockfile

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm build

      - name: Publish to npm
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm publish
